name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      
    - name: Build
      run: npm run build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: dist
      
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: Build
        path: dist
        
    - name: Setup Yandex CLI
      uses: avtocod/yc-actions/cli@master
      with:
        yc-api-key: ${{ secrets.YC_TOKEN }}
        yc-folder-id: b1guv2o6d0bqb1qg866u
        yc-cloud-id: b1gti8m4j4n4veck1g1u


    - name: Deploy to Yandex Object Storage
      run: |
        yc s3 cp --recursive ./dist s3://scormbucket
      env:
        YC_TOKEN: ${{ secrets.YC_TOKEN }}
        BUCKET_NAME: scormbucket
