name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      
    - name: Build
      run: npm run build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: dist
      
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: Build
        path: dist

    - name: Install Yandex CLI
      run: |
        curl https://storage.yandexcloud.net/yandexcloud-yc-install/install.sh | bash
      env:
        YC_TOKEN: ${{ secrets.YC_TOKEN }}

    - name: Deploy to Yandex Object Storage
      run: |
        yc config set token $YC_TOKEN
        yc s3 cp --recursive ./dist s3://scormbucket
      env:
        YC_TOKEN: ${{ secrets.YC_TOKEN }}
        BUCKET_NAME: scormbucket
